### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [ReznichenkoSergey/SiteProject#1]
1)
требования к высоте не выполнены
2)
шрифт не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/92297691-abf80d00-ef4a-11ea-86a6-568e17ef9aaf.png)

3)
невалидный css
![image](https://user-images.githubusercontent.com/8464662/92297735-f4172f80-ef4a-11ea-8903-c81436cf92c7.png)

4)
контейнер как блок здесь нелогичен
![image](https://user-images.githubusercontent.com/8464662/92297748-15781b80-ef4b-11ea-8e5d-ab46ad7c2acd.png)

**Comment by ReznichenkoSergey** [comment]
Добрый день. Исправлены выявленные ошибки
git:   https://github.com/ReznichenkoSergey/SiteProject
link:  https://reznichenkosergey.github.io/SiteProject/

сб, 5 сент. 2020 г. в 07:41, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
2 - не исправлено.
проверьте размер для всех разрешений.

5)
отступы не соответствуют макету
![image](https://user-images.githubusercontent.com/8464662/92311229-f49cde00-efbd-11ea-8a08-29ec960fa835.png)

6)
размер не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/92311234-fff00980-efbd-11ea-8837-6fa4578219a5.png)
![image](https://user-images.githubusercontent.com/8464662/92311281-70972600-efbe-11ea-8402-0341b9d137a7.png)

7)
отступы не соответствуют для некоторых разрешений
![image](https://user-images.githubusercontent.com/8464662/92311239-0b433500-efbe-11ea-8236-57fa2c8b13f6.png)

8)
проверяйте размер шрифта для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/92311247-28780380-efbe-11ea-8461-aad0b81e96dc.png)

9)
цвет не соответствует
![image](https://user-images.githubusercontent.com/8464662/92311259-434a7800-efbe-11ea-9ed6-1a99bb2a0839.png)

10)
размер не соответствует
![image](https://user-images.githubusercontent.com/8464662/92311270-5c532900-efbe-11ea-92c6-449eac3ef6ae.png)
![image](https://user-images.githubusercontent.com/8464662/92311276-66752780-efbe-11ea-960e-e224f640ee7c.png)

**Comment by ReznichenkoSergey** [comment]
Добрый день. Исправления по выявленным ошибкам
git:   https://github.com/ReznichenkoSergey/SiteProject
link:  https://reznichenkosergey.github.io/SiteProject/

сб, 5 сент. 2020 г. в 21:26, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
2 - не исправлено
10 - не исправлено

**Comment by ReznichenkoSergey** [comment]
Добрый вечер. Вроде поправил 2 и 10 ошибки.

пн, 7 сент. 2020 г. в 16:48, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
а ссылки для проверки?

пн, 7 вер. 2020 о 21:13 Sergey <notifications@github.com> пише:

**Comment by ReznichenkoSergey** [comment]
Добрый день. Сылки для проверки.
git: https://github.com/ReznichenkoSergey/SiteProject
link: https://reznichenkosergey.github.io/SiteProject/

ср, 9 сент. 2020 г. в 15:23, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
2- не исправлено.

11) разделитель расположен неправильно.
проверяйте для всех разрешений.
![image](https://user-images.githubusercontent.com/8464662/92599840-738e6100-f2b3-11ea-91e7-508bee50e19b.png)

**Comment by ReznichenkoSergey** [comment]
Добрый день.
п.2 - поправил (размер шрифта)
PS
п.11 ... разделитель откорректировал по горизонтали ... по вертикали
выравниваю посередине, т.к. в макете grid-template.xd - он расположен
посередине, но съедается часть текстовой информации на меньших разрешениях.
А в мастер-шаблоне на вашем гите - он размещен по верхней границе текста.
Вы упор ставили на grid-template.xd... поэтому по вертикали он размещен
посередине.

Сылки для проверки.
git: https://github.com/ReznichenkoSergey/SiteProject
link: https://reznichenkosergey.github.io/SiteProject/

ср, 9 сент. 2020 г. в 15:44, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
11 - не исправлено.
>>> Вы упор ставили на grid-template.xd... 

именно так.

>>> т.к. в макете grid-template.xd - он расположен посередине, но съедается часть текстовой информации на меньших разрешениях.

ничего подобного в макете нет.

12)
неправильный размер блока
![image](https://user-images.githubusercontent.com/8464662/92681838-6a46d800-f337-11ea-919a-b4f9ab9bebf3.png)

**Comment by ReznichenkoSergey** [comment]
Добрый день. Вроде получилось. Сылки для проверки.
git: https://github.com/ReznichenkoSergey/SiteProject
link: https://reznichenkosergey.github.io/SiteProject/

чт, 10 сент. 2020 г. в 07:33, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
ничего не было исправлено

чт, 10 вер. 2020 о 14:39 Sergey <notifications@github.com> пише:

**Comment by ReznichenkoSergey** [comment]
Ссылки для проверки.
> git: https://github.com/ReznichenkoSergey/SiteProject
> link: https://reznichenkosergey.github.io/SiteProject/

чт, 10 сент. 2020 г. в 16:11, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
12 - не исправлено

**Comment by ReznichenkoSergey** [comment]
Мне уже паддинги сниться скоро будут ... я правильно понял шаблон:
при разрешении >992px верхний и нижний паддинги = 30px и мин. высота блока
= 120px,
при <=992  верхний и нижний паддинги = 20px и  мин. высота блока = 100px
... в этом проблема?

Ссылки для проверки.
git: https://github.com/ReznichenkoSergey/SiteProject
link: https://reznichenkosergey.github.io/SiteProject/

чт, 10 сент. 2020 г. в 21:30, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
чт, 10 вер. 2020 о 22:38 Sergey <notifications@github.com> пише:

> Мне уже паддинги сниться скоро будут ... я правильно понял шаблон:
> при разрешении >992px верхний и нижний паддинги = 30px и мин. высота блока
> = 120px,
> при <=992 верхний и нижний паддинги = 20px и мин. высота блока = 100px
> ... в этом проблема?
>
нет, не правильно поняли.
на скрине однозначно указана и описана проблема.

**Comment by ReznichenkoSergey** [comment]
Дошло. Спасибо
Ссылки для проверки.
git: https://github.com/ReznichenkoSergey/SiteProject
link: https://reznichenkosergey.github.io/SiteProject/

пт, 11 сент. 2020 г. в 08:46, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
да, теперь все отлично, работа принята.

пт, 11 вер. 2020 о 10:20 Sergey <notifications@github.com> пише:
